# Size a HPP plant based on a simplified HPP model using EGO parallel

## Learning Objectives
1. Performing hybrid power plant sizing optimization using simplified model.
2. Analyzing the hybrid power plant design for different locations.

## Exercise A

Sizing a hybrid power plant consists on designing the following parameters:

### Design Variables

**Wind Plant design:**

- Number of wind turbines in the wind plant [-] (`Nwt`)
- Wind power installation density [MW/km2] (`wind_MW_per_km2`): This parameter controls how closely spaced are the turbines, which in turns affect how much wake losses are present.

**PV Plant design:**

- Solar plant power capacity [MW] (`solar_MW`)

**Battery Storage design:**

- Battery power [MW] (`b_P`)
- Battery energy capacity in hours [MWh] (`b_E_h `): Battery storage capacity in hours of full battery power (`b_E = b_E_h * b_P `). 
- Cost of battery power fluctuations in peak price ratio [-] (`cost_of_batt_degr`): This parameter controls how much penalty is given to do ramps in battery power in the HPP operation.


### Objective function

NPV/CAPEX: Net present value over total CAPEX.

In [1]:
import pandas as pd
from hydesign.Parallel_EGO_simple import EGO_path
from hydesign.examples import examples_filepath

In [2]:
examples_sites = pd.read_csv(f'{examples_filepath}examples_sites.csv', index_col=0)
examples_sites

,case,name,longitude,latitude,altitude,input_ts_fn,sim_pars_fn,price_fn,price_col
0,India,Indian_site_good_wind,77.500226,8.334294,679.803454,India/input_ts_Indian_site_good_wind.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price
1,India,Indian_site_good_solar,68.542204,23.542099,29.883557,India/input_ts_Indian_site_good_solar.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price
2,India,Indian_site_bad_solar_bad_wind,77.916878,17.292316,627.424643,India/input_ts_Indian_site_bad_solar_bad_wind.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price
3,Europe,France_good_solar,4.229736,44.422011,204.000000,Europe/input_ts_France_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R
4,Europe,France_good_wind,-0.864258,48.744116,302.000000,Europe/input_ts_France_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R
5,Europe,France_bad_solar_n_wind,2.167969,47.428087,140.000000,Europe/input_ts_France_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R
6,Europe,Germany_bad_solar_n_wind,10.766602,49.310798,442.000000,Europe/input_ts_Germany_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_ME
7,Europe,Germany_good_wind,7.873535,53.287111,5.000000,Europe/input_ts_Germany_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_NW
8,Europe,Denmark_good_solar,11.813965,55.397760,42.000000,Europe/input_ts_Denmark_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_E
9,Europe,Denmark_good_wind,8.594398,56.227322,85.000000,Europe/input_ts_Denmark_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_W
10,Europe,Netherlands,6.833000,53.450000,2.000000,Europe/input_ts_Netherlands.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NL_R

In [3]:
EGO_parallel_P2X = f'{EGO_path}Parallel_EGO_P2X.py'

### Running Parallel EGO Simple

In [ ]:
%run $EGO_parallel_P2X

Selected example site:
---------------------------------------------------
case                                         Europe
name                               France_good_wind
longitude                                 -0.864258
latitude                                  48.744116
altitude                                      302.0
input_ts_fn    Europe/input_ts_France_good_wind.csv
sim_pars_fn                     Europe/hpp_pars.yml
price_fn                   Europe/2030-EL_PRICE.csv
price_col                                      FR_R
Name: 4, dtype: object




Sizing a HPP plant at France_good_wind:

longitude = -0.864258
latitude = 48.744116
altitude = 302.0



longitude =longitude =longitude =longitude =   -0.864258-0.864258
-0.864258
 latitude =
latitude =-0.864258 latitude =
48.744116 48.744116latitude =48.744116


altitude =48.744116altitude =altitude =
302.0302.0302.0altitude =


302.0
longitude =longitude =longitude =longitude = -0.864258
 -0.864258-0.864258latitude =-0.864258


latitude =latitude =48.744116latitude =
 48.74411648.744116altitude =
48.744116
 altitude =
altitude =302.0 altitude =
302.0 302.0
302.0

longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
longitude = -0.864258
latitude = 48.744116
altitude = 302.0
Initial 16 simulations took 7.15 minutes

Update sm and extract candidate points took 0.03 minutes

/home/gupta/miniconda3/envs/hydesign/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

longitude =longitude =longitude = -0.864258
longitude =longitude =-0.864258-0.864258latitude =

latitude =longitude = longitude =   latitude =-0.86425848.744116 -0.864258 48.744116
48.744116


-0.864258altitude =latitude =
latitude =-0.864258altitude =
  altitude =
latitude = 302.048.744116 48.744116latitude = 302.0

302.0
 48.744116
altitude =
altitude =
  altitude =302.0302.0

302.048.744116

altitude = 302.0